dpaste/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"",include("dpasteapp.urls")),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dpasteapp/urls.py
from .views import *
from django.urls import path


app_name = "dpasteapp"

urlpatterns = [
    path(r'', DpasteController.as_view(),name = "dpaste_form"),
    path(r'about',aboutDpaste,name = "dpaste_about"),
    path(r'history', DpasteListView.as_view(),name = "dpastelist"),
    path(r'<str:link>', DpasteView.as_view(),name = "dpaste_view"),
]

dpasteapp/models.py
from django.db import models
import base64

LANGUAGE_CHOICES = (
        ('text', 'TEXT'),
        ('c', 'C'),
        ('cpp', 'C++'),
        ('py', 'PYTHON'),
        ('json', 'JSON'),
 )

EXPIRY_CHOICES = (
        (1, '1 Day'),
        (7, '1 Week'),
        (30, '1 Month'),
        (365, '1 Year')
)

# Create your models here.

class DjangoPastebin(models.Model):
    identification = models.IntegerField()
    link = models.CharField(max_length=256)
    content = models.TextField()
    title = models.CharField(max_length=256)
    user = models.CharField(max_length=256)
    language = models.CharField(max_length=5, choices=LANGUAGE_CHOICES, default='text')
    image = models.FileField(max_length=256,upload_to="templates/upload_pictures",null=True, blank=True,
                                  default="templates/upload_pictures/noimage.png")
    video = models.FileField(max_length=256, upload_to="templates/upload_videos", null=True, blank=True,
                             default="templates/upload_pictures/no-video.jpg")
    created = models.DateTimeField(auto_now=True)
    expiry = models.IntegerField(choices= EXPIRY_CHOICES, default=1)

    def __str__(self):
        return self.user

dpasteapp/views/dpastebin.py
from dpasteapp.models import *
from django import forms
from django.views.generic import *
from django.shortcuts import *
import hashlib
import datetime
from django.db.models import *
from django.utils import timezone
import jsbeautifier

class DpasteForm(forms.ModelForm):
    class Meta:
        model = DjangoPastebin
        exclude = ['id','identification','link','created']
        widgets = {
            'content':forms.Textarea(attrs={'class':'form-control'}),
            'language': forms.Select(choices=LANGUAGE_CHOICES),
            'image':forms.FileInput(attrs={'class': 'form-control'}),
            'video': forms.FileInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'user': forms.TextInput(attrs={'class': 'form-control'}),
            'expiry': forms.Select(choices=EXPIRY_CHOICES),
        }


class DpasteController(CreateView):
    model = DjangoPastebin
    form_class = DpasteForm
    template_name = 'dpasteform.html'

    def post(self, request, *args, **kwargs):
        form = DpasteForm(request.POST,request.FILES)

        if form.is_valid():
            data = form.save(commit=False)
            data.created = datetime.datetime.now()
            data.identification = 0
            data.save()
            data.link = hashlib.shake_128(str(data.id).encode()).hexdigest(5)
            resp = redirect( '/' + data.link)
            if 'value' in request.COOKIES:
                data.identification = int(request.COOKIES.get('value'))

            else:
                try:
                    value = DjangoPastebin.objects.aggregate(Max("identification"))
                    resp.set_cookie('value', value["identification__max"]+1)
                    data.identification = value["identification__max"]+1
                except Exception as e:
                    resp.set_cookie('value', 1)
                    data.identification = 1

            data.save()
            return resp

        return redirect('dpasteapp:dpaste_form')

def check_link(date,expiry):
    if (date + datetime.timedelta(days=expiry)) < timezone.now():
        return True
    else:
        return False

class DpasteView(View):
    def get(self, request, link):
        try:
            data = DjangoPastebin.objects.get(link=link)
        except ObjectDoesNotExist:
            return render(
                request,
                template_name='error.html'
            )
        if check_link(data.created, data.expiry):
            return render(
                request,
                template_name='error.html'
            )

        expiry_in = data.created + datetime.timedelta(days=data.expiry) - timezone.now()
        expiry_str = ""
        if expiry_in.days > 0:
            expiry_str += str(expiry_in.days) + "Days, "
        if (expiry_in.seconds // (3600)) % 24 > 0:
            expiry_str += str((expiry_in.seconds // (3600)) % 24) + "Hours, "
        if (expiry_in.seconds // 60) % (60) > 0:
            expiry_str += str((expiry_in.seconds // (60)) % 60) + "Minutes"
        elif expiry_in.seconds > 0:
            expiry_str += str(expiry_in.seconds) + "Seconds"

        opts = jsbeautifier.default_options()
        opts.indent_size = 4
        res = jsbeautifier.beautify(data.content, opts)

        return render(
            request,
            'dpasteview.html',
            context={
                'data': res,
                'img':data.image,
                'video': data.video,
                'expiry': expiry_str,
                'form': DpasteForm,
            }
        )

class DpasteListView(ListView):
    model = DjangoPastebin
    template_name = 'dpaste_list.html'
    context_object_name = 'list'

    def get_queryset(self):
        print("value")
        if 'value' in self.request.COOKIES:
            value = int(self.request.COOKIES.get('value'))
            list = DjangoPastebin.objects.filter(identification = value).order_by('-created') if value >= 1 else []
            for s in list:
                if check_link(s.created, s.expiry):
                    s.link = None
            return list
        return []

    def get_context_data(self,**kwargs):
        context = super(DpasteListView,self).get_context_data(**kwargs)
        return context

def aboutDpaste(request):
    return render(request, "about.html")

dpasteapp/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <style>
        html{
            min-height:100%;
        }
    </style>
</head>
<body>
<nav class="nav navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Dpaste</a>
      </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="nav navbar-nav navbar-right" href="{% url 'dpasteapp:dpaste_about' %}">  ABOUT  </a></li>
            <li><a class="nav navbar-nav navbar-right" href="{% url 'dpasteapp:dpastelist' %}">  HISTORY  </a></li>
            <li><a class="nav navbar-nav navbar-right" href="{% url 'dpasteapp:dpaste_form' %}" >  NEW  </a></li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
<footer class="small pt-4 mt-4">
    <center><p class="text-muted">By M.M.Lakshmi Priya</p></center>
</footer>
</body>
</html>

dpasteapp/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>
{% extends '_base.html' %}
{% block content %}
<div class="container">

    <center>
        <h2>Welcome to Paste World !!!</h2>
    <hr>
        <p>Here you can share anything with your friends by generating a simple url</p><br>
        <p>After submitting the enough details when you click on submit button you are redirected to link page which
        consists your information along with url in the browser. you can access this url anywhere.</p><br>
        <p>Your information is maintained by your browser cookies. Once you deleted the cookies in your browser, you cannot
        access your urls by your history page , but the information is maintained in our database,still you can access the url.</p><br>
        <p><b>History</b> : This will give information about generated urls by you.</p><br>
        <p><b>New</b> : This will redirect to home page</p>
    </center>
</div>
{% endblock %}
</body>
</html>

dpasteapp/templates/dpaste_list.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
{% extends "_base.html" %}

{% block content %}
<h1>Your Links</h1>
    <div class="container">
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th>Title</th>
            <th>CreatedOn</th>
            <th>LifeTime</th>
            <th>Link</th>
        </tr>
        </thead>
        {% for s in list %}
            <tr>
                <td>{{s.title}}</td>
                <td>{{ s.created }} UTC</td>
                <td>{{s.expiry}} Days</td>
                {% if s.link is None %}
                    <td>Expired</td>
                {% else %}
                    <td><a href="/{{s.link}}">{{s.link}}</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
    </div>
        {% endblock %}
</body>
</html>

dpasteapp/templates/dpasteform.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<body>
{% extends '_base.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="col-sm-6 col-xs-12">
            <div class="input-group row">
                <label>Content:</label>
                {{form.content}}
            </div>
            <br>
            <div class="input-group row">
                <label>Type:
                {{form.language}}</label>
            </div>
            <br>
             <div class="input-group row">
                <label>Image:
                 {{form.image}}</label>
            </div>
            <br>
            <div class="input-group row">
                <label>Video:
                 {{form.video}}</label>
            </div>
            <br>
            <div class="input-group row">
                <label>Title:</label>
                {{form.title}}
            </div>
            <br>
            <div class="input-group row">
                <label>Name:</label>
                {{form.user}}
            </div>
            <br>
            <div class="input-group row">
                <label>Expiry:
                {{form.expiry}}</label>
            </div>
            <br>
        <div class="row">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        </div>
    </form>
</div>
{% endblock %}
</body>
</html>

dpasteapp/templates/dpasteview.html
<!DOCTYPE html>
<html lang="en">
<body>
{% extends '_base.html' %}
{% block content %}
<div class="container">
    <label>Content  : </label>
    <textarea class="form-control" rows="7" readonly>{{data}}</textarea><br>
    {% if img.url != '/media/templates/upload_pictures/noimage.png' or video.url != '/media/templates/upload_pictures/no-video.jpg'%}
    <label> Images/Videos :</label><br>
    <div align = "center">
    {% if img.url != '/media/templates/upload_pictures/noimage.png' %}
                    <img src="{{ img.url }}" width="250" height="250" hspace="20" align = "left">
    {% endif %}
    {% if video.url != '/media/templates/upload_pictures/no-video.jpg' %}
                    <video width="320" height="250" controls>
                            <source src="{{ video.url }}" type="video/mp4">
                    </video>
    {% endif %}
        {% endif %}
        </div>
    <hr>
    <h4 align = "center">{{expiry}}</h4>
</div>
{% endblock %}
</body>
</html>

dpasteapp/templates/dummy.html
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="" class="navbar-brand"><h1>Dpaste</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto"  style="text-align:center;">
            <li class="nav-item"><a href="{% url 'dpasteapp:dpaste_form' %}" class="nav-link">New</a></li>
            <li class="nav-item"><a href="{% url 'dpasteapp:dpastelist' %}" class="nav-link">History</a></li>
        </ul>
    </div>
</nav>
<center>
{% block content %} {% endblock %}
</center>
<footer class="small pt-4 mt-4">
    <center><p class="text-muted">By M.M.Lakshmi Priya</p></center>
</footer>
</body>

dpasteapp/templates/error.html
<!DOCTYPE html>
<html lang="en">
<body>

{% extends '_base.html' %}
{% block content %}

    <h3>Once check the link you have given</h3>
{% endblock %}

</body>
</html>